### ISSUE TITLE
please don't calculate versioning based on build time

### ISSUE THREAD

**Issue by IzzySoft** [frimtec/secure-sms-proxy#368]
You currently set `versionCode` and `versionName` [based on build time](https://github.com/frimtec/secure-sms-proxy/blob/master/app/build.gradle#L12) – which makes reproducing your builds rather difficult (see: [Reproducible Builds](https://reproducible-builds.org/) and also [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). Could you please instead use something that's not dependent on the time the app was built? Thanks in advance!

**Comment by frimtec** [comment]
Hi Izzy

I see your point but the current solution takes off the burden to set vcode and vname in the repo before releasing.

I thought it was quite common to replace  vname with the release name of GitHub.
To calculate the vcode from time ensures unique and growing version codes.

Would it help to calculate vcode based on vname instead of time?

**Comment by IzzySoft** [comment]
Everything that remains the same regardless of the time the app is being build, yeah. To see what's happening here, this is the build recipe I ended up with to have your app RB:

```yaml
        build:
          - chmod +x gradlew
          - sed -r 's/VERSION_NAME=\$version/VERSION_NAME=3.2.7/' -i app/version.properties
          - sed -r 's/int vcode = Integer.*/int vcode = 1873545/' -i app/build.gradle
          - ./gradlew assembleRelease
          - git clone -b v0.2.8 https://github.com/obfusk/reproducible-apk-tools.git
          - reproducible-apk-tools/zipalign.py --pad-like-apksigner --replace app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-realigned.apk
```

It's the two `sed` commands I'm concerned about here, as they need manual adjustment on each build currently (I don't remember what versionName it came up with – but IIRC it was `3.0.0-dev` – looks like gradle didn't replace the `$version` in `version.properties` properly).

(before you ask: yes, I know I can concatenate `sed` commands, but intentionally did not – for better readability, as I'd have to update that for each release :see_no_evil:)

**Comment by frimtec** [comment]
I will rewrite my workflows so that the code under the release tag will have fixed vcode and vname values instead of placeholders.
This should solve your problem.
Will do that before the next release is done.

**Comment by IzzySoft** [comment]
Thanks a lot! :star_struck:

**Comment by frimtec** [comment]
I released 3.2.8 a few moments ago.

If you look at the version information in the code base at the release tag (https://github.com/frimtec/secure-sms-proxy/blob/3.2.8/app/version.properties) you will see that the values are now fixed and not evaluated during build time.
Therefore you should be able to remove all the special handling now.

Just close the issue when you can confirm that all is fine.

**Comment by IzzySoft** [comment]
Confirmed! This recipe here produced a clean RB:

```yaml
  - tag: 3.2.8
    apks:
      - apk_pattern: app-release\.apk
        apk_url: https://github.com/frimtec/secure-sms-proxy/releases/download/3.2.8/app-release.apk
        build:
          - chmod +x gradlew
          - ./gradlew assembleRelease
          - git clone -b v0.2.8 https://github.com/obfusk/reproducible-apk-tools.git
          - reproducible-apk-tools/zipalign.py --pad-like-apksigner --replace app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-realigned.apk
          - mv app/build/outputs/apk/release/*realigned.apk /outputs/unsigned.apk
```

Thanks a lot!
